import React, { Component } from 'react';
import "../../styles.scss";

class DiscussionThreads extends Component {

    constructor(props) {
        super(props);

        this.state = {
            thread: "events"
        };
        this.onClick = this.onClick.bind(this);


    }

    onClick = event => {
        this.setState({
            thread: event.target.value
        })
        console.log(this.state.thread);
    }



    render() {
        return (
            <div className="bg_color_1">
            <div className="container margin_80_55">
                <div className="main_title_2">
                <span><em /></span>
                <h3>News and Events</h3>
                <p>Cum doctus civibus efficiantur in imperdiet deterruisset. I would love to change the lipsum, but appreciate the autogenerated version</p>
                </div>
                <div className="row">
                <div className="col-lg-6">
                    <a className="box_news" href="#0">
                    <figure><img src="http://placehold.it/400x267" alt />
                        <figcaption><strong>28</strong>Dec</figcaption>
                    </figure>
                    <ul>
                        <li>Author</li>
                        <li>20.15.18</li>
                    </ul>
                    <h4>Pri oportere scribentur eu</h4>
                    <p>Cu eum alia elit, usu in eius appareat, deleniti sapientem honestatis eos ex. In ius esse ullum vidisse....</p>
                    </a>
                </div>
                {/* /box_news */}
                {/* /box_news */}
                <div className="col-lg-6">
                    <a className="box_news" href="#0">
                    <figure><img src="http://placehold.it/400x267" alt />
                        <figcaption><strong>28</strong>Dec</figcaption>
                    </figure>
                    <ul>
                        <li>Author</li>
                        <li>20.15.18</li>
                    </ul>
                    <h4>Pri oportere scribentur eu</h4>
                    <p>Cu eum alia elit, usu in eius appareat, deleniti sapientem honestatis eos ex. In ius esse ullum vidisse....</p>
                    </a>
                </div>
                {/* /box_news */}
                <div className="col-lg-6">
                    <a className="box_news" href="#0">
                    <figure><img src="http://placehold.it/400x267" alt />
                        <figcaption><strong>28</strong>Dec</figcaption>
                    </figure>
                    <ul>
                        <li>Author</li>
                        <li>20.15.18</li>
                    </ul>
                    <h4>Pri oportere scribentur eu</h4>
                    <p>Cu eum alia elit, usu in eius appareat, deleniti sapientem honestatis eos ex. In ius esse ullum vidisse....</p>
                    </a>
                </div>
                {/* /box_news */}
                <div className="col-lg-6">
                    <a className="box_news" href="#0">
                    <figure><img src="http://placehold.it/400x267" alt />
                        <figcaption><strong>28</strong>Dec</figcaption>
                    </figure>
                    <ul>
                        <li>Author</li>
                        <li>20.15.18</li>
                    </ul>
                    <h4>Pri oportere scribentur eu</h4>
                    <p>Cu eum alia elit, usu in eius appareat, deleniti sapientem honestatis eos ex. In ius esse ullum vidisse....</p>
                    </a>
                </div>
                {/* /box_news */}
                </div>
                {/* /row */}
                <p className="btn_home_align"><a href="#0" className="btn_1 rounded">View all Posts</a></p>
            </div>
            {/* /container */}
            </div>
        );
    }
}
export default DiscussionThreads;